[package]
name = "etib"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
bytemuck = { version = "1", features = ["derive"] }
env_logger = "0.11"
glam = { version = "0.32", features = ["bytemuck"] }
log = "0.4"
pollster = "0.4"
rand = "0.10.1"
rustc-hash = "2.1.2"
wgpu = "29"
winit = "0.30"
