[package]
name = "etib"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
bytemuck = { workspace = true }
cgmath = "0.18"
env_logger = "0.11"
etib-core = { path = "../etib-core" }
image = { version = "0.25.9", features = ["hdr"] }
log = { workspace = true }
pollster = "0.4"
wgpu = { workspace = true }
winit = "0.30"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
tempfile = "3.15.0"
